export const galleryContainer = document.querySelector(".gallery")
export const numberColumns = document.querySelector("#numberCol")
export const numberGallery = document.querySelector("#numberGallery")
export const introContainer = document.querySelector("#intro")
export const settingsContainer = document.querySelector("#settings")
export const metroid = document.querySelector("#metroid")
export const pokemon = document.querySelector("#pokemon")
export const zelda = document.querySelector("#zelda")